#!/bin/bash

# Helper script to access services within Docker containers
# Generated by start-system.sh for the anomaly detection system

# Access service by name
case "$1" in
  lstm)
    docker exec lstm-autoencoder curl -X $2 http://localhost:5000/$3
    ;;
  supervised)
    docker exec supervised curl -s -X $2 http://localhost:8000/$3
    ;;
  logs)
    docker compose logs -f $2
    ;;
  *)
    echo "Usage: ./access-services.sh [lstm|supervised|logs] [GET|POST|service_name] [endpoint]"
    echo "Examples:"
    echo "  ./access-services.sh lstm GET learning/status"
    echo "  ./access-services.sh supervised GET health"
    echo "  ./access-services.sh supervised GET health"
    echo "  ./access-services.sh logs lstm-autoencoder"
    ;;
esac
