[supervisord]
nodaemon=true

[program:flink]
command=/opt/flink/bin/start-flink.sh
directory=/opt/flink
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/flink.err.log
stdout_logfile=/var/log/supervisor/flink.out.log
